### ISSUE TITLE
KSP gets stuck on black loading screen when starting with StockScatterTextures 

### ISSUE THREAD

**Issue by pag00** [Gameslinx/Parallax-Continued#12]
Game runs fine without Parallax Continued, I installed everything as described [here](https://github.com/Gameslinx/Parallax-Continued/tree/master?tab=readme-ov-file#installation-instructions). My GameData folder now looks as follows:

```
GameData % ls -1 
000_ClickThroughBlocker
000_Harmony
000_KSPBurst
000_TexturesUnlimited
000_Toolbar
001_ToolbarControl
112x_TU_Stock Recolour_v0_3_12
190_TU_APP_v0_1_0
AirplanePlus
Blackrack_TUFX.cfg
EnvironmentalVisualEnhancements
FerramAerospaceResearch
Firespitter
KerbalChangelog
Kopernicus
ModularFlightIntegrator
ModuleManager.4.2.3.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree
Parallax
Parallax_StockPlanetTextures
Parallax_StockScatterTextures
Parallax_StockTerrainTextures
ReStock
ReStockPlus
Scatterer
ScattererAtmosphereCache
Shabby
Squad
SquadExpansion
StockScattererConfigs
StockVolumetricClouds
TUFX
TURD_MH-BG_stable_002
TURD_blackrack.cfg
toolbar-settings.dat
zzz_Deferred

```

When I start the game now, everything seems to load fine until the black screen with the spinning planets, where it will remain. In my [KSP.log](https://github.com/user-attachments/files/18037738/KSP.log) the last normal line is related to `Parallax_StockScatterTextures`, so I suspect an issue with this folder. 
I tried starting without it, which works, but then the terrain seems to be back to stock (I guessed so, without any textures).

**Comment by Gameslinx** [comment]
Hiya, you're running Parallax Continued on an Apple M4 Pro. Apple devices are unsupported because they lack support for Compute Shaders.
See this in the log file: 
`[Parallax] Beginning config load
[LOG 12:38:02.423] [Parallax] System Information: 
[LOG 12:38:02.423] [Parallax] GPU Name: Apple M4 Pro
[LOG 12:38:02.423] [Parallax] Renderer Name: OpenGLCore
[LOG 12:38:02.423] [Parallax] Supports Compute Shaders: False
[LOG 12:38:02.423] [Parallax] Supports Async Readback: False
[LOG 12:38:02.424] [Parallax] Available VRAM: 36864
[LOG 12:38:02.424] [Parallax] Available RAM: 49152
[ERR 12:38:02.424] [Parallax] This system is not capable of running Parallax.`

Apple discontinued OpenGL support many years ago before Compute Shader support. The only way to run Parallax on an Apple device is to find a way to run either DirectX11 or a later version of OpenGL. On Linux, Proton will do this, but I'm not sure of a way to do it for a Mac.

**Send me your email or contact me via patreon and I'll issue you a full refund**.

**Comment by pag00** [comment]
Ah that sucks, Parallax looks so good! Thanks for the quick answer though, I'll write you on Patreon

**Comment by Gameslinx** [comment]
No worries, it's completely out of my control I'm afraid! Best of luck
